### ISSUE TITLE
Deprecation warning message in Azure DevOps Pipeline

### ISSUE THREAD

**Issue by tfabris** [chrisism/VSTS.ChocolateyTools#23]
@chrisism - 

We are using this tool in our Azure DevOps Pipeline. This tool triggers a deprecation warning message when it is used in a YML file. The warning is causing problems in our pipeline. I opened a support ticket with Microsoft about it and they denied responsibility and told me to contact you here.

Microsoft says that you need to update your tool to use Node 10 as described here: https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md

Is this something that could be updated?

Thanks!

Warning message:
```2021-12-09T21:47:18.2595932Z ==============================================================================
2021-12-09T21:47:18.2596299Z Task         : Chocolatey - Install Package
2021-12-09T21:47:18.2596606Z Description  : Installs a package using Chocolatey
2021-12-09T21:47:18.2596848Z Version      : 1.1.1
2021-12-09T21:47:18.2597068Z Author       : Jungerius IT
2021-12-09T21:47:18.2597290Z Help         : 
2021-12-09T21:47:18.2597568Z ==============================================================================
2021-12-09T21:47:18.2672113Z ##[warning]Task 'ChocoInstallPackage' (1.1.1) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
```

**Comment by chrisism** [comment]
I will see if I can make time and pick this up soon enough. However, I was planning to deprecate this extension. There are other alternatives available. So let me know if those are sufficient.

**Comment by tfabris** [comment]
I totally understand about wanting to stop supporting old extensions when they get the API rug yanked out from under them like that. I did the same thing once, with a Chrome extension I had written.

I can work around this issue by just using the chocolatey command line directly.

I have a different extension in the same YML file, facing the same kind of deprecation, which is going to be trickier to fix, but I'll tackle that one separately.

Thanks!

**Comment by tfabris** [comment]
Solution:

Old code (gives deprecation warning:):
```
  # -----------------------------------------------------------------------------
  # Install the latest Paket tool via Chocolatey, this should
  # theoretically ensure that it's updated to the latest version.
  # -----------------------------------------------------------------------------
  - task: ChocoInstallPackage@1
    displayName: Install Paket
    inputs:
      packageId: 'paket'
```

New code (seems to work for the same thing):
```
  # -----------------------------------------------------------------------------
  # Upgrade the latest Paket tool via Chocolatey, this should either
  # install it if it's not installed, and/or ensure that it's updated.
  # -----------------------------------------------------------------------------
  - task: PowerShell@2
    displayName: Upgrade Paket
    inputs:
      targetType: 'inline'
      failOnStderr: true
      script: |
        choco upgrade paket -y
```
